{{- if  .Values.hpa   }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ $.Release.Name }}
    helm.sh/chart: {{ $.Chart.Version  }}
spec:
  minReplicas: {{ .Values.hpa.minReplicas | default 2 }}
  maxReplicas: {{ .Values.hpa.maxReplicas | default 4 }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.targetCPUUtilizationPercentage | default 80 }}

{{ end }}
