{{- if  .Values.external_secrets_aws }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  labels:
    app: {{ $.Release.Name }}
    helm.sh/chart: {{ $.Chart.Version  }}
  name: {{ .Release.Name }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: global-secret-store-aws
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.external_secrets_aws.secret }}
{{ end }}