{{- if  .Values.pdb }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $.Release.Name }}
  labels:
    app: {{ $.Release.Name }}
    helm.sh/chart: {{ $.Chart.Version  }}
spec:
  {{- if  .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable | default 1 }}
  {{ else }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable | default 1 }}
  {{ end }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}
      helm.sh/chart: {{ $.Chart.Version  }}

{{ end }}