---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}
  labels:
    app: {{ $.Release.Name }}
    helm.sh/chart: {{ $.Chart.Version  }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Release.Name }}
      helm.sh/chart: {{ $.Chart.Version  }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}
        helm.sh/chart: {{ $.Chart.Version  }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .deployment.image }}:{{ .deployment.tag }}
        imagePullPolicy: Always
        resources:
            requests:
              memory: {{ .deployment.memory | default "128Mi" }}
              ephemeral-storage: {{ .deployment.ephemeral_storage | default "1Gi" }}
              cpu: {{ .deployment.cpu | default "500m" }}
            limits:
              memory: {{ .deployment.memory | default "128Mi" }}
              ephemeral-storage: {{ .deployment.ephemeral_storage | default "1Gi" }}
              cpu: {{ .deployment.cpu | default "500m" }}
        envFrom:
        - secretRef:
          name: {{ .Release.Name }}
        ports:
        - containerPort: {{ .deployment.port | default 3000 }}
