{{- if  .Values.external_secrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: global-secret-store-vault
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.external_secrets.secret }}
{{ end }}