{{- if  .Values.external_secrets_alfa }}
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ $.Release.Name }}
    helm.sh/chart: {{ $.Chart.Version  }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: global-secret-store-vault
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}
  dataFrom:
    - key: {{ .Values.external_secrets.secret }}
{{ end  }}